const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
// Ordine delle proprietà: memoria, linearità, invarianza nel tempo.
const examples = [
 ['Resistore ideale', 'Ingresso: corrente $i(t)$. Uscita: tensione $v(t)=Ri(t)$. Resistenza costante, temperatura mantenuta costante; effetti capacitivi e induttivi trascurati.', [0,1,1], 'Basta la corrente attuale. Moltiplicare per R rispetta la sovrapposizione; R non dipende dall’orologio.'],
 ['Potenza nel resistore', 'Ingresso: corrente $i(t)$. Uscita: potenza istantanea $p(t)=Ri^2(t)$. Resistore ideale con R costante e temperatura controllata; non si considera l’evoluzione termica.', [0,0,1], 'La potenza dipende solo dalla corrente attuale, ma raddoppiando la corrente quadruplica. La legge resta la stessa nel tempo.'],
 ['Resistore che si autoriscalda', 'Ingresso: corrente. Uscita: tensione $v=R(T)i$. La temperatura interna evolve per effetto della potenza dissipata e dello scambio termico. R dipende da T con coefficiente non nullo; ambiente e coefficienti costanti.', [1,0,1], 'La temperatura conserva gli effetti della storia. Il riscaldamento quadratico accoppia corrente e resistenza: non vale la sovrapposizione. Le leggi non dipendono esplicitamente dal tempo; si confrontano preparazioni iniziali uguali.'],
 ['Temperatura programmata: tensione', 'Ingresso: corrente. Uscita: tensione $v(t)=R(t)i(t)$. Un dispositivo esterno impone una temperatura non costante secondo un orologio, rendendo R(t) non costante e indipendente dalla corrente. Autoriscaldamento ed effetti dinamici elettrici trascurati.', [0,1,0], 'Non serve la storia della corrente. R(t) moltiplica linearmente l’ingresso, ma ripetere lo stesso ingresso a un altro orario può produrre una tensione diversa.'],
 ['Temperatura programmata: potenza', 'Stesse ipotesi del caso precedente, ma uscita uguale alla potenza $p(t)=R(t)i^2(t)$ e ingresso uguale alla corrente. Il programma esterno resta fissato quando si ritarda l’ingresso.', [0,0,0], 'Il valore attuale basta; il quadrato viola la linearità; il programma esterno rende il modello tempo-variante. Questa riga ha tutte le caselle vuote.'],
 ['Circuito RC ideale', 'Ingresso: tensione del generatore. Uscita: tensione sul condensatore. R e C costanti, circuito inizialmente a riposo. La tensione dipende dalla carica già presente nel condensatore; il modello matematico è nell’approfondimento avanzato sul circuito RC. Negli esperimenti traslati si trasla coerentemente anche la preparazione.', [1,1,1], 'La carica immagazzinata introduce memoria. Con stato iniziale nullo vale la sovrapposizione. I coefficienti costanti rendono il modello tempo-invariante.'],
 ['Diodo nel modello statico', 'Ingresso: tensione ai capi. Uscita: corrente. Relazione esponenziale della giunzione a temperatura costante, capacità e fenomeni di immagazzinamento di carica trascurati; funzionamento fuori dalla rottura inversa.', [0,0,1], 'Il modello statico usa solo la tensione attuale. La relazione esponenziale non rispetta la sovrapposizione. I parametri sono costanti nel tempo.'],
 ['Termostato con isteresi', 'Ingresso: temperatura misurata. Uscita: comando acceso/spento. Accende sotto 19 °C, spegne sopra 21 °C, conserva il comando precedente nella fascia intermedia. Soglie fisse e stessa preparazione iniziale per ogni esperimento.', [1,0,1], 'Nella fascia intermedia serve il comando precedente. Soglie e comando binario non rispettano la sovrapposizione. La regola non cambia con l’orario.'],
 ['Serbatoio a sezione costante', 'Ingresso: variazione della portata netta, con segno. Uscita: variazione del livello rispetto a un riferimento, inizialmente nulla. Sezione A costante: la variazione di livello è proporzionale al volume netto aggiunto. Il livello conserva gli effetti delle portate precedenti; si trascurano saturazioni, trabocco e svuotamento.', [1,1,1], 'Il livello accumula gli effetti della portata. Nel modello delle variazioni, con stato iniziale nullo, vale la sovrapposizione. La legge ha coefficienti costanti.'],
 ['Quadrato dell’ingresso', 'Elaboratore ideale di segnali normalizzati: ingresso u e uscita $y(t)=u^2(t)$. Calcolo istantaneo, senza limiti di ampiezza o ritardi nel modello.', [0,0,1], 'Usa solo il campione attuale; il quadrato viola la sovrapposizione; la formula non dipende dall’orologio.'],
 ['Ritardo con guadagno programmato', 'Elaboratore discreto: conserva un campione e restituisce $y[n]=k[n]u[n-1]$, con $k[n]=2+\\sin(\\pi n/4)$ prescritto dall’esterno. Il programma k non viene traslato con l’ingresso.', [1,1,0], 'Il campione precedente richiede memoria. Ritardo e moltiplicazione per k[n] sono lineari. Il guadagno esplicito non costante rende il sistema tempo-variante.'],
 ['Quadrato ritardato con guadagno programmato', 'Elaboratore di segnali normalizzati: $y[n]=k[n](u[n-1])^2$, con $k[n]=2+\\sin(\\pi n/4)$ prescritto dall’esterno. Conserva il campione precedente e ne calcola il quadrato.', [1,0,0], 'Il ritardo introduce memoria, il quadrato introduce non linearità e il guadagno programmato introduce variabilità nel tempo.']
];
const props = ['Memoria', 'Linearità', 'Invarianza nel tempo'];
const sets = {memoria: [[0,5,7,3],[0]], linearita:[[0,1,2,6,9],[1]], invarianza:[[0,2,3,10],[2]], completa:[examples.map((_,i)=>i),[0,1,2]]};
for (const [id,[rows,cols]] of Object.entries(sets)) {
 let s = `<!-- Generato da scripts/build_classification.cjs -->\n::: {.classification-exercise #esercizio-${id}}\n\nSpunta solo le proprietà presenti. Conferma ogni riga prima di verificare. Le soluzioni commentate sono disponibili sotto ogni tabella.\n\n`;
 s += '| Sistema: ingresso, uscita e ipotesi | '+cols.map(p=>props[p]).join(' | ')+' |\n|---|'+cols.map(()=>':---:').join('|')+'|\n';
 for(const i of rows) {const [name,desc,answers]=examples[i]; s += `| **${name}.** ${desc} | `+cols.map(p=>`[□]{.answer-cell data-answer="${!!answers[p]}"}`).join(' | ')+' |\n';}
 s += '\n::: {.classification-solutions}\n\n<details>\n<summary>Soluzioni commentate</summary>\n\n';
 for(const i of rows) { const [name,,answers,why]=examples[i]; s += `- **${name}:** `+cols.map(p=>`${props[p]} **${answers[p]?'sì':'no'}**`).join('; ')+`. ${why}\n\n`; }
 s+='</details>\n\n:::\n\n:::\n';
 fs.writeFileSync(path.join(root,'corsi/sistemi-automatici/moduli',`_classificazione-${id}.qmd`),s);
}
console.log('Generate quattro tabelle di classificazione.');
