// Run after quarto render. No external packages required.
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'../_site'),names=['resistore','condensatore','induttore','diodo','transistor'];
let files=[];function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isDirectory())walk(f);else if(f.endsWith('.html'))files.push(f);}}walk(root);
let total=0;
for(const f of files){const html=fs.readFileSync(f,'utf8');for(const tag of html.matchAll(/<a\b[^>]*\bclass="[^"]*\bcomponent-link\b[^"]*"[^>]*>/g)){const href=tag[0].match(/\bhref="([^"]+)"/);assert(href,'Missing href');const u=href[1];assert(!u.endsWith('.qmd'),'Unresolved source URL: '+u);const dest=u.startsWith('/')?path.join(root,u.replace(/^\/didattica-interattiva\//,'/')):path.resolve(path.dirname(f),u);assert(fs.existsSync(dest),'Broken component link: '+u);assert.notEqual(path.resolve(dest),path.resolve(f),'Automatic self link: '+f);assert(tag[0].includes('data-glossary-definition='),'Missing tooltip');total++;}}
for(const name of names){const html=fs.readFileSync(path.join(root,'risorse/componenti',name+'.html'),'utf8');assert(html.includes('assets/componenti/'),'Missing diagram: '+name);if(['resistore','condensatore','induttore'].includes(name))for(let i=1;i<=6;i++)assert(html.includes('id="livello-'+i+'"'),'Missing level '+i+' in '+name);}
const sample=fs.readFileSync(path.join(root,'corsi/tpsee-elettronici/modulo-1.html'),'utf8');for(const name of names)assert(sample.includes('/componenti/'+name+'.html'),'Missing module entry point: '+name);
const exceptions=fs.readFileSync(path.join(root,'corsi/tpsee-elettrotecnici/modulo-4.html'),'utf8');assert.equal((exceptions.match(/class="no-component-link"/g)||[]).length,5);assert(!/class="no-component-link"[^>]*>\s*<a/.test(exceptions));assert(total>0);console.log(`PASS: ${names.length} component pages, ${total} automatic links, levels, tooltips and non-electrical exceptions.`);
